services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  cache:
    image: arm64v8/redis:6-bookworm
    container_name: cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache_data:/data

  db:
    container_name: database
    image: arm64v8/postgres:trixie
    restart: unless-stopped

    environment:
      POSTGRES_DB: superdawn_db
      POSTGRES_USER: sudawn
      POSTGRES_PASSWORD: example

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data:
  cache_data:
  minio_data:
