/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedCreateOrganizationRouteImport } from './routes/_protected/create-organization'
import { Route as ProtectedScopeIdRouteImport } from './routes/_protected/$scopeId'
import { Route as ProtectedScopeIdWorkspaceRouteImport } from './routes/_protected/$scopeId/workspace'
import { Route as ProtectedScopeIdPropertyRouteImport } from './routes/_protected/$scopeId/property'
import { Route as ProtectedScopeIdDashboardRouteImport } from './routes/_protected/$scopeId/dashboard'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedCreateOrganizationRoute =
  ProtectedCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedScopeIdRoute = ProtectedScopeIdRouteImport.update({
  id: '/$scopeId',
  path: '/$scopeId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedScopeIdWorkspaceRoute =
  ProtectedScopeIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => ProtectedScopeIdRoute,
  } as any)
const ProtectedScopeIdPropertyRoute =
  ProtectedScopeIdPropertyRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => ProtectedScopeIdRoute,
  } as any)
const ProtectedScopeIdDashboardRoute =
  ProtectedScopeIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedScopeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$scopeId': typeof ProtectedScopeIdRouteWithChildren
  '/create-organization': typeof ProtectedCreateOrganizationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof ProtectedIndexRoute
  '/$scopeId/dashboard': typeof ProtectedScopeIdDashboardRoute
  '/$scopeId/property': typeof ProtectedScopeIdPropertyRoute
  '/$scopeId/workspace': typeof ProtectedScopeIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/$scopeId': typeof ProtectedScopeIdRouteWithChildren
  '/create-organization': typeof ProtectedCreateOrganizationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof ProtectedIndexRoute
  '/$scopeId/dashboard': typeof ProtectedScopeIdDashboardRoute
  '/$scopeId/property': typeof ProtectedScopeIdPropertyRoute
  '/$scopeId/workspace': typeof ProtectedScopeIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/$scopeId': typeof ProtectedScopeIdRouteWithChildren
  '/_protected/create-organization': typeof ProtectedCreateOrganizationRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/$scopeId/dashboard': typeof ProtectedScopeIdDashboardRoute
  '/_protected/$scopeId/property': typeof ProtectedScopeIdPropertyRoute
  '/_protected/$scopeId/workspace': typeof ProtectedScopeIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$scopeId'
    | '/create-organization'
    | '/login'
    | '/register'
    | '/'
    | '/$scopeId/dashboard'
    | '/$scopeId/property'
    | '/$scopeId/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$scopeId'
    | '/create-organization'
    | '/login'
    | '/register'
    | '/'
    | '/$scopeId/dashboard'
    | '/$scopeId/property'
    | '/$scopeId/workspace'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/$scopeId'
    | '/_protected/create-organization'
    | '/_public/login'
    | '/_public/register'
    | '/_protected/'
    | '/_protected/$scopeId/dashboard'
    | '/_protected/$scopeId/property'
    | '/_protected/$scopeId/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/create-organization': {
      id: '/_protected/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof ProtectedCreateOrganizationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$scopeId': {
      id: '/_protected/$scopeId'
      path: '/$scopeId'
      fullPath: '/$scopeId'
      preLoaderRoute: typeof ProtectedScopeIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$scopeId/workspace': {
      id: '/_protected/$scopeId/workspace'
      path: '/workspace'
      fullPath: '/$scopeId/workspace'
      preLoaderRoute: typeof ProtectedScopeIdWorkspaceRouteImport
      parentRoute: typeof ProtectedScopeIdRoute
    }
    '/_protected/$scopeId/property': {
      id: '/_protected/$scopeId/property'
      path: '/property'
      fullPath: '/$scopeId/property'
      preLoaderRoute: typeof ProtectedScopeIdPropertyRouteImport
      parentRoute: typeof ProtectedScopeIdRoute
    }
    '/_protected/$scopeId/dashboard': {
      id: '/_protected/$scopeId/dashboard'
      path: '/dashboard'
      fullPath: '/$scopeId/dashboard'
      preLoaderRoute: typeof ProtectedScopeIdDashboardRouteImport
      parentRoute: typeof ProtectedScopeIdRoute
    }
  }
}

interface ProtectedScopeIdRouteChildren {
  ProtectedScopeIdDashboardRoute: typeof ProtectedScopeIdDashboardRoute
  ProtectedScopeIdPropertyRoute: typeof ProtectedScopeIdPropertyRoute
  ProtectedScopeIdWorkspaceRoute: typeof ProtectedScopeIdWorkspaceRoute
}

const ProtectedScopeIdRouteChildren: ProtectedScopeIdRouteChildren = {
  ProtectedScopeIdDashboardRoute: ProtectedScopeIdDashboardRoute,
  ProtectedScopeIdPropertyRoute: ProtectedScopeIdPropertyRoute,
  ProtectedScopeIdWorkspaceRoute: ProtectedScopeIdWorkspaceRoute,
}

const ProtectedScopeIdRouteWithChildren =
  ProtectedScopeIdRoute._addFileChildren(ProtectedScopeIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedScopeIdRoute: typeof ProtectedScopeIdRouteWithChildren
  ProtectedCreateOrganizationRoute: typeof ProtectedCreateOrganizationRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedScopeIdRoute: ProtectedScopeIdRouteWithChildren,
  ProtectedCreateOrganizationRoute: ProtectedCreateOrganizationRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
