/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedCreateOrganizationRouteImport } from './routes/_protected/create-organization'
import { Route as ProtectedScopeIdRouteImport } from './routes/_protected/$scopeId'
import { Route as ProtectedScopeIdIndexRouteImport } from './routes/_protected/$scopeId/index'
import { Route as ProtectedScopeIdPropertyRouteImport } from './routes/_protected/$scopeId/property'
import { Route as ProtectedScopeIdAccountRouteImport } from './routes/_protected/$scopeId/account'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/_public/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCreateOrganizationRoute =
  ProtectedCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedScopeIdRoute = ProtectedScopeIdRouteImport.update({
  id: '/$scopeId',
  path: '/$scopeId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedScopeIdIndexRoute = ProtectedScopeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedScopeIdRoute,
} as any)
const ProtectedScopeIdPropertyRoute =
  ProtectedScopeIdPropertyRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => ProtectedScopeIdRoute,
  } as any)
const ProtectedScopeIdAccountRoute = ProtectedScopeIdAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedScopeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$scopeId': typeof ProtectedScopeIdRouteWithChildren
  '/create-organization': typeof ProtectedCreateOrganizationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof ProtectedIndexRoute
  '/$scopeId/account': typeof ProtectedScopeIdAccountRoute
  '/$scopeId/property': typeof ProtectedScopeIdPropertyRoute
  '/$scopeId/': typeof ProtectedScopeIdIndexRoute
}
export interface FileRoutesByTo {
  '/create-organization': typeof ProtectedCreateOrganizationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof ProtectedIndexRoute
  '/$scopeId/account': typeof ProtectedScopeIdAccountRoute
  '/$scopeId/property': typeof ProtectedScopeIdPropertyRoute
  '/$scopeId': typeof ProtectedScopeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/$scopeId': typeof ProtectedScopeIdRouteWithChildren
  '/_protected/create-organization': typeof ProtectedCreateOrganizationRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/$scopeId/account': typeof ProtectedScopeIdAccountRoute
  '/_protected/$scopeId/property': typeof ProtectedScopeIdPropertyRoute
  '/_protected/$scopeId/': typeof ProtectedScopeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$scopeId'
    | '/create-organization'
    | '/login'
    | '/register'
    | '/'
    | '/$scopeId/account'
    | '/$scopeId/property'
    | '/$scopeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-organization'
    | '/login'
    | '/register'
    | '/'
    | '/$scopeId/account'
    | '/$scopeId/property'
    | '/$scopeId'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/$scopeId'
    | '/_protected/create-organization'
    | '/_public/login'
    | '/_public/register'
    | '/_protected/'
    | '/_protected/$scopeId/account'
    | '/_protected/$scopeId/property'
    | '/_protected/$scopeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/create-organization': {
      id: '/_protected/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof ProtectedCreateOrganizationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$scopeId': {
      id: '/_protected/$scopeId'
      path: '/$scopeId'
      fullPath: '/$scopeId'
      preLoaderRoute: typeof ProtectedScopeIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$scopeId/': {
      id: '/_protected/$scopeId/'
      path: '/'
      fullPath: '/$scopeId/'
      preLoaderRoute: typeof ProtectedScopeIdIndexRouteImport
      parentRoute: typeof ProtectedScopeIdRoute
    }
    '/_protected/$scopeId/property': {
      id: '/_protected/$scopeId/property'
      path: '/property'
      fullPath: '/$scopeId/property'
      preLoaderRoute: typeof ProtectedScopeIdPropertyRouteImport
      parentRoute: typeof ProtectedScopeIdRoute
    }
    '/_protected/$scopeId/account': {
      id: '/_protected/$scopeId/account'
      path: '/account'
      fullPath: '/$scopeId/account'
      preLoaderRoute: typeof ProtectedScopeIdAccountRouteImport
      parentRoute: typeof ProtectedScopeIdRoute
    }
  }
}

interface ProtectedScopeIdRouteChildren {
  ProtectedScopeIdAccountRoute: typeof ProtectedScopeIdAccountRoute
  ProtectedScopeIdPropertyRoute: typeof ProtectedScopeIdPropertyRoute
  ProtectedScopeIdIndexRoute: typeof ProtectedScopeIdIndexRoute
}

const ProtectedScopeIdRouteChildren: ProtectedScopeIdRouteChildren = {
  ProtectedScopeIdAccountRoute: ProtectedScopeIdAccountRoute,
  ProtectedScopeIdPropertyRoute: ProtectedScopeIdPropertyRoute,
  ProtectedScopeIdIndexRoute: ProtectedScopeIdIndexRoute,
}

const ProtectedScopeIdRouteWithChildren =
  ProtectedScopeIdRoute._addFileChildren(ProtectedScopeIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedScopeIdRoute: typeof ProtectedScopeIdRouteWithChildren
  ProtectedCreateOrganizationRoute: typeof ProtectedCreateOrganizationRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedScopeIdRoute: ProtectedScopeIdRouteWithChildren,
  ProtectedCreateOrganizationRoute: ProtectedCreateOrganizationRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
